### ISSUE TITLE
Traceback when launching the scanner

### ISSUE THREAD

**Issue by eax64** [vigilate/program_scanner#5]
Here is what happen when I run the program on my machine:

```
$> ./scanner.py 
Traceback (most recent call last):
  File "./scanner.py", line 174, in <module>
    main()
  File "./scanner.py", line 162, in main
    progs += get_dpkg_progs()
  File "./scanner.py", line 65, in get_dpkg_progs
    while not output[0].endswith("==="):
IndexError: list index out of range
```

OS: archlinux
python version: 3.5.1

dpkg is installed and and when I run the same dpkg command from the script (dpkg -l) i do not have any output.

**Comment by ampotos** [comment]
the scanner need to handle empty result from every package manager
